name: blog

services:

    blog-db:
        image: 'mysql'
        deploy:
            replicas: 1
            update_config:
                order: start-first
                failure_action: rollback
                delay: 10s
            rollback_config:
                parallelism: 1
                order: start-first
        healthcheck:
            test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost' ]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - blog-app-store:/var/lib/mysql
        ports:
            - '3306:3306'
        networks:
            - blog-app-net

    blog-server:
        image: sachinjdv7/blog-app:v1
        deploy:
            replicas: 1
            update_config:
                order: start-first
                failure_action: rollback
                delay: 10s
            rollback_config:
                parallelism: 1
                order: start-first
        healthcheck:
            test: [ "CMD", "wget", '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/health' ]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
        ports:
            - "3000:3000"
        environment:
            - DB_HOST=blog-db
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_NAME=blogdb
            - MYSQL_ROOT_PASSWORD=root
            - NODE_HOST="{{.Node.Hostname}}"
        depends_on:
            - blog-db
        networks:
            - blog-app-net

volumes:
    blog-app-store:
networks:
    blog-app-net:
